Loading the dataset and performing an initial inspection to determine whether the data are clean, consistent and ready for exploratory data analysis. This first step includes cheking for missing values, duplicate records, outliers, incorrect data types, and any inconcistencies thay may affect the quality of the analysis.

In [2]:
# uploading the dataset
from google.colab import files
uploaded = files.upload()

Saving BNdetailing_2025_messydata.csv to BNdetailing_2025_messydata.csv

In [3]:
# Framing the dataset using pandas library
import pandas as pd
df_BNdetailing = pd.read_csv('BNdetailing_2025_messydata.csv')

# Visualizing the data types
df_BNdetailing.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5104 entries, 0 to 5103
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Job_ID              5104 non-null   int64
 1   Date                5104 non-null   object
 2   Customer_ID         5104 non-null   object
 3   Customer_Name       5104 non-null   object
 4   Customer_Type       5104 non-null   object
 5   Service             5104 non-null   object
 6   Channel             4949 non-null   object
 7   County              5104 non-null   object
 8   City                5104 non-null   object
 9   Base_Price_Jan_Jun  5104 non-null   int64
 10  Final_Price         5104 non-null   object
 11  Tip                 5104 non-null   int64
 12  Total_Amount        5104 non-null   float64
 13  Duration_Minutes    5104 non-null   int64
 14  Payment_Method      5104 non-null   object
 15  Discount_Code       2521 non-null   object
 16  Rating              4253 non-null   float64
dtypes: float64(2), int64(4), object(11)
memory usage: 678.0+ KB

In [4]:
# Visualizing the first 20 rows of the dataset
df_BNdetailing.head(200)

,Job_ID,Date,Customer_ID,Customer_Name,Customer_Type,Service,Channel,County,City,Base_Price_Jan_Jun,Final_Price,Tip,Total_Amount,Duration_Minutes,Payment_Method,Discount_Code,Rating
0,1,13-04-2025,CUST0947,Emma Davis,New,Basic Wash,Instagram,Sarasota,Venice,40,40,10,50.0,60,cash,NaN,4.0
1,2,2025-12-15 00:00:00,CUST0632,Liam Anderson,New,Full Detail,Word of Mouth,Sarasota,North Port,150,160,20,180.0,175,cash,SUMMER10,4.0
2,3,2025-09-28 00:00:00,CUST0045,ALEX MARTINEZ,New,Interior Detail,youtube,Sarasota,Sarasota,90,94,15,109.0,37,Venmo,VIP,5.0
3,4,2025-04-17 00:00:00,CUST0811,Ava Johnson,New,Premium Wash,TikTok,Charlotte,Punta Gorda,70,68,20,88.0,90,Cash,NaN,4.0
4,5,2025-03-13 00:00:00,CUST0522,Emma Davis,New,Interior Detail,FaceBook,Sarasota,Sarasota,90,85,15,100.0,150,cash,NaN,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,195,2025-06-29 00:00:00,CUST1001,ava taylor,New,Ceramic Coating,Referral,Sarasota,North Port,350,352,0,352.0,80,CARD,VIP,NaN
196,196,2025-04-23 00:00:00,CUST1005,Lewis Anderson,New,Full Detail,referral,Sarasota,North Port,150,150,20,170.0,59,Cash,SUMMER10,4.0
197,197,2025-11-14 00:00:00,CUST0944,NOAH MILLER,Returning,Full Detail,social,Charlotte,Port Charlotte,150,170,0,170.0,169,Card,NaN,3.0
198,198,2025-02-21 00:00:00,CUST0345,Emma Martinez,New,Full Detail,Instagram,Charlotte,Punta Gorda,150,155,10,165.0,146,cash,NEWCUSTOMER,4.0
199,199,2025-09-25 00:00:00,CUST0722,Ava Johnson,New,Full Detail,YOUTUBE,Sarasota,Sarasota,150,$165.00,20,185.0,141,Venmo,NaN,4.0

In [5]:
df_BNdetailing.tail(200)

,Job_ID,Date,Customer_ID,Customer_Name,Customer_Type,Service,Channel,County,City,Base_Price_Jan_Jun,Final_Price,Tip,Total_Amount,Duration_Minutes,Payment_Method,Discount_Code,Rating
4904,4806,2025-07-06 00:00:00,CUST1145,mary johnson,Returning,Full Detail,YOUTUBE,Sarasota,North Port,150,163,0,163.0,176,Cash,NEWCUSTOMER,NaN
4905,4806,2025-07-06 00:00:00,CUST1145,mary johnson,Returning,Full Detail,YOUTUBE,Sarasota,North Port,150,163,0,163.0,176,Cash,NEWCUSTOMER,NaN
4906,4807,2025-08-20 00:00:00,CUST1077,Ava Smith,Returning,Full Detail,referral,Sarasota,North Port,150,160,0,160.0,167,Venmo,NaN,5.0
4907,4808,2025-09-12 00:00:00,CUST1090,Lewis Wilson,Returning,Full Detail,facebook,Charlotte,Port Charlotte,150,160,20,180.0,64,CARD,NaN,5.0
4908,4809,2025-04-14 00:00:00,CUST1129,Noah Johnson,Returning,Full Detail,Instagram,Sarasota,Venice,150,150,0,150.0,140,cash,SUMMER10,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5099,4996,2025-02-25 00:00:00,CUST0536,Olivia Anderson,Returning,Premium Wash,Instagram,Sarasota,North Port,70,70,15,85.0,107,Cash App,NaN,4.0
5100,4997,2025-12-26 00:00:00,CUST1111,Lewis Miller,Returning,Ceramic Coating,instagram,Charlotte,Punta Gorda,350,385,0,385.0,90,Venmo,NaN,4.0
5101,4998,2025-04-20 00:00:00,CUST0704,LIAM MARTINEZ,Returning,Premium Wash,facebook,Charlotte,Port Charlotte,70,75,0,75.0,93,Card,SUMMER10,NaN
5102,4999,2025-07-11 00:00:00,CUST1108,Emma Brown,Returning,Ceramic Coating,youtube,Charlotte,Port Charlotte,350,390,15,405.0,78,CARD,NEWCUSTOMER,NaN
5103,5000,2025-04-03 00:00:00,CUST1120,lewis miller,Returning,Interior Detail,NaN,Charlotte,Punta Gorda,90,90,0,90.0,42,Venmo,NaN,5.0

In [6]:
# Describing the numerical columns
df_BNdetailing.describe(include= "all")

,Job_ID,Date,Customer_ID,Customer_Name,Customer_Type,Service,Channel,County,City,Base_Price_Jan_Jun,Final_Price,Tip,Total_Amount,Duration_Minutes,Payment_Method,Discount_Code,Rating
count,5104.000000,5104,5104,5104,5104,5104,4949,5104,5104,5104.000000,5104,5104.000000,5104.000000,5104.000000,5104,2521,4253.000000
unique,NaN,608,1187,600,2,5,22,2,5,NaN,94,NaN,NaN,NaN,7,3,NaN
top,NaN,2025-06-03 00:00:00,CUST0234,Liam Johnson,Returning,Full Detail,YouTube,Sarasota,Punta Gorda,NaN,165,NaN,NaN,NaN,Venmo,NEWCUSTOMER,NaN
freq,NaN,27,11,20,3889,1053,286,2888,1159,NaN,187,NaN,NaN,NaN,769,859,NaN
mean,2499.337187,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,137.364812,NaN,8.030956,152.465321,105.074451,NaN,NaN,4.181989
std,1442.644168,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,108.655634,NaN,7.520448,115.074003,43.640695,NaN,NaN,0.746762
min,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.000000,NaN,-5.000000,35.000000,30.000000,NaN,NaN,3.000000
25%,1249.750000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,70.000000,NaN,0.000000,75.000000,67.000000,NaN,NaN,4.000000
50%,2498.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,90.000000,NaN,5.000000,102.000000,105.000000,NaN,NaN,4.000000
75%,3750.250000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,150.000000,NaN,15.000000,170.000000,143.000000,NaN,NaN,5.000000
max,5000.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,350.000000,NaN,20.000000,410.000000,180.000000,NaN,NaN,5.000000

After visualizing the dataset , some data types are incorrect and there are also inconsistent data in many columns . before before starting the analysis, we must clean the dataset for better result.

Cleanning the date column by using pd.to_datetime method to parse it.

In [7]:
# Making a copy of the Date column for safety inspection
Date_column = df_BNdetailing['Date'].copy()

# Parsing the date column copied with multiple formats
Date_parse = pd.to_datetime(Date_column, format='mixed', dayfirst=True)

In [8]:
#  Checking for remaining NaT values if existed
Date_parse.isna().sum()

np.int64(0)

In [9]:
# Updating the 'Date' column in the main DataFrame
df_BNdetailing['Date'] = Date_parse

# Verifying the update by checking the DataFrame info
df_BNdetailing.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5104 entries, 0 to 5103
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Job_ID              5104 non-null   int64
 1   Date                5104 non-null   datetime64[ns]
 2   Customer_ID         5104 non-null   object
 3   Customer_Name       5104 non-null   object
 4   Customer_Type       5104 non-null   object
 5   Service             5104 non-null   object
 6   Channel             4949 non-null   object
 7   County              5104 non-null   object
 8   City                5104 non-null   object
 9   Base_Price_Jan_Jun  5104 non-null   int64
 10  Final_Price         5104 non-null   object
 11  Tip                 5104 non-null   int64
 12  Total_Amount        5104 non-null   float64
 13  Duration_Minutes    5104 non-null   int64
 14  Payment_Method      5104 non-null   object
 15  Discount_Code       2521 non-null   object
 16  Rating              4253 non-null   float64
dtypes: datetime64[ns](1), float64(2), int64(4), object(10)
memory usage: 678.0+ KB

Cleanning the final price column by convering it to a numeric data using pd.to_numeric function.

In [10]:
# Copying the Final_Price column before the convertion
final_price_column = df_BNdetailing['Final_Price'].copy()

# Removing the '$' sign and converting  to numeric column
final_price_numeric = pd.to_numeric(final_price_column.astype(str).str.replace('$', '', regex=False), errors='coerce')

# Checking for NaN values if existed and the data types
final_price_numeric.isna().sum()
final_price_numeric.info()

# Updating the final price column to the main dataframe
df_BNdetailing['Final_Price'] = final_price_numeric

<class 'pandas.core.series.Series'>
RangeIndex: 5104 entries, 0 to 5103
Series name: Final_Price
Non-Null Count  Dtype
--------------  -----
5104 non-null   float64
dtypes: float64(1)
memory usage: 40.0 KB

Cleanning the final price column by converting it to a numeric data using pd.to_numeric function

In [11]:
# Making a copy of the column for safety inspection
total_amount_column = df_BNdetailing['Total_Amount'].copy()

# Converting the column and removing the $ sign
total_amount_numeric = pd.to_numeric(total_amount_column.astype(str).str.replace('$', '', regex=False), errors='coerce')

# Checking for NaN values if existed and the data type
total_amount_numeric.isna().sum()
total_amount_numeric.info()

# Updating the total_amount column
df_BNdetailing['Total_Amount'] = total_amount_numeric

df_BNdetailing.info()

<class 'pandas.core.series.Series'>
RangeIndex: 5104 entries, 0 to 5103
Series name: Total_Amount
Non-Null Count  Dtype
--------------  -----
5104 non-null   float64
dtypes: float64(1)
memory usage: 40.0 KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5104 entries, 0 to 5103
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Job_ID              5104 non-null   int64
 1   Date                5104 non-null   datetime64[ns]
 2   Customer_ID         5104 non-null   object
 3   Customer_Name       5104 non-null   object
 4   Customer_Type       5104 non-null   object
 5   Service             5104 non-null   object
 6   Channel             4949 non-null   object
 7   County              5104 non-null   object
 8   City                5104 non-null   object
 9   Base_Price_Jan_Jun  5104 non-null   int64
 10  Final_Price         5104 non-null   float64
 11  Tip                 5104 non-null   int64
 12  Total_Amount        5104 non-null   float64
 13  Duration_Minutes    5104 non-null   int64
 14  Payment_Method      5104 non-null   object
 15  Discount_Code       2521 non-null   object
 16  Rating              4253 non-null   float64
dtypes: datetime64[ns](1), float64(3), int64(4), object(9)
memory usage: 678.0+ KB

Converting the data type of the tip column

In [12]:
# Converting 'Tip' column from int64 to float64
df_BNdetailing['Tip'] = df_BNdetailing['Tip'].astype(float)

# Verify the data type conversion
df_BNdetailing['Tip'].info()

# Fixing the negative values
df_BNdetailing['Tip'] = df_BNdetailing['Tip'].abs()

<class 'pandas.core.series.Series'>
RangeIndex: 5104 entries, 0 to 5103
Series name: Tip
Non-Null Count  Dtype
--------------  -----
5104 non-null   float64
dtypes: float64(1)
memory usage: 40.0 KB

Cleanning the customer name

In [13]:
# Making a copy of the customer name column
customer_name_column = df_BNdetailing['Customer_Name'].copy()

# Removing any leading/trailing white spaces from the customer name
customer_name_column = customer_name_column.str.strip()

# Normalizing internal spaces (replace multiple spaces with a single space)
customer_name_column = customer_name_column.str.replace(r'\s+', ' ', regex=True)

# Converting the names in title format
customer_name_column = customer_name_column.str.title()

# Cheking for non string values in the column name
non_string_names = customer_name_column[customer_name_column.apply(lambda x: not isinstance(x, str))]
if non_string_names.empty:
    print("No non-string values found in the 'Customer_Name' column.")
else:
    print(f"Non-string value found: {non_string_names}")


# Updating the customer_name column to the main data frame
df_BNdetailing['Customer_Name'] = customer_name_column

# Visualizing the customer name column after the cleaning
df_BNdetailing['Customer_Name']

No non-string values found in the 'Customer_Name' column.

0            Emma Davis
1         Liam Anderson
2         Alex Martinez
3           Ava Johnson
4            Emma Davis
             ...
5099    Olivia Anderson
5100       Lewis Miller
5101      Liam Martinez
5102         Emma Brown
5103       Lewis Miller
Name: Customer_Name, Length: 5104, dtype: object

Cleanning the channel column

In [14]:
# Making a copy of the channel column
channel_column = df_BNdetailing['Channel'].copy()

# Normalizing all text as string , removing leading and trailling space, and format all text in lower case.
channel_column = channel_column.astype(str).str.strip().str.lower()

# Mapping the messy values to clean categories
channel_mapping = {'instagram': 'Instagram','insta': 'Instagram',
                  'facebook': 'Facebook','fb': 'Facebook',
                  'youtube': 'Youtube', 'yotube':'Youtube',
                  'tiktok':'TikTok','tik tok': 'TikTok',
                  'referral': 'Referral', 'referred':'Referral',
                  'word of mouth':'Referral',
                  'social': 'Other'}
channel_column = channel_column.map(channel_mapping)

# Filling NaN values (unmapped channels) with 'Unknown'
channel_column = channel_column.fillna('Unknown')

# Updating the 'Channel' column in the main DataFrame with the cleaned values
df_BNdetailing['Channel'] = channel_column

# Displaying unique unmapped values (NaNs)
unmapped_channels = df_BNdetailing['Channel'][df_BNdetailing['Channel'].isna()].unique()
if len(unmapped_channels) > 0:
    print("Unmapped channels:\n", unmapped_channels)
else:
    print("All channels are mapped.")

# Displaying the unique values in the updated channel column
df_BNdetailing['Channel'].unique()

All channels are mapped.

array(['Instagram', 'Referral', 'Youtube', 'TikTok', 'Facebook', 'Other',
       'Unknown'], dtype=object)

Cleaning the payment method colummn

In [15]:
# Making a copy of the payment method column and visualizing the unique values
payment_method_column = df_BNdetailing['Payment_Method'].copy()

# Visualizing the unique values of the payment method
payment_method_column.unique()

# Normalizing the values as string and lowercase format
payment_method_column = payment_method_column.astype(str).str.strip().str.lower()

# Mapping the messy values to clean category
payment_method_mapping = {'cash':'Cash', 'venmo':'Venmo','cash app':'Cash App','card':'Card','zelle':'Zelle'}
payment_method_column = payment_method_column.map(payment_method_mapping)

# Displaying the unique unmapped values
unmapped_payment_method = df_BNdetailing['Payment_Method'][payment_method_column.isna()].unique()
if len(unmapped_payment_method) > 0:
    print("Unmapped payment methods:\n", unmapped_payment_method)
else:
    print ('all values are mapped')

# Updating the payment_method column to the main dataframe
df_BNdetailing['Payment_Method'] = payment_method_column

all values are mapped

Fixing duplicated rows

In [16]:
# Finding duplicate rows and displaying the amount
duplicate_rows = df_BNdetailing.duplicated().sum()
print(f"Number of duplicate rows: {duplicate_rows}")

# Removing the duplicated rows
df_BNdetailing = df_BNdetailing.drop_duplicates()

Number of duplicate rows: 104

Handling missing values

In [17]:
# Checking the missing values in the main dataframe
df_BNdetailing.isna().sum()

# Making a copy of the Rating column
rating_column = df_BNdetailing['Rating'].copy()

# Handling missing values in "Rating" column by filling NaN with "No Feedback"
rating_column.fillna('No Feedback', inplace=True)

# Updating the rating column to the main dataframe
df_BNdetailing['Rating'] = rating_column

# Making a copy of the Discount_Code column
discount_code_column = df_BNdetailing['Discount_Code'].copy()

# Handling missing values in "Discount_Code" column by filling NaN with 'No Discount'
discount_code_column.fillna('No Discount', inplace=True)

# Updatting the Discount_Code column to the main datafframe
df_BNdetailing['Discount_Code'] = discount_code_column

/tmp/ipython-input-3992180124.py:8: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'No Feedback' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  rating_column.fillna('No Feedback', inplace=True)

Creating the clean and final dataset

In [18]:
# Creating the clean and final dataset
df_BNdetailing.to_csv('BNdetailing_2025_clean.csv', index=False)

In [19]:
from google.colab import files
files.download('BNdetailing_2025_clean.csv')